name: lint_and_test

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run project setup
        uses: ./.github/actions/setup
        with:
          python-version: '3.13'
      - name: Run linters
        run: make lint

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12', '3.13']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run project setup
        uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        run: uv run pytest --cov=elizur --cov-report=xml

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
